name: Update hub

on:
  workflow_dispatch:

jobs:
  update-jina-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.JINA_DEV_BOT }}
      - run: |
          sudo apt-get update -y
          sudo apt-get install python3.7 git python3-distutils python3-pip -y
          pip3 install gitpython ruamel.yaml PyGithub semver
          git clone --depth=1 https://$DEV_BOT_TOKEN@github.com/jina-ai/jina-hub.git
          output=$(python3.7 scripts/jina-hub-update.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$output"
        id: step1

